package org.mrdlib.partnerContentManager;

public enum MdlDocumentType {

	UNKNOWN,
	JOURNAL_ARTICLE,
	CONFERENCE_ARTICLE,
	BOOK,
	CHAPTER_IN_BOOK,
	WORKSHOP_ARTICLE,
	TECH_REPORT,
	REVIEW_BOOK,
	THESIS_UNSPECIFIED,
	GOVERNMENT_DOCUMENT,
	REVIEW_FILM,
	MONOGRAPH,
	PATENT,
	REVIEW_SOFTWARE,
	WEBSITE,
	WORK_IN_PROGRESS_PAPER,
	NEWS_ARTICLE,
	LETTER_FROM_EDITOR,
	COMMENT,
	CONFERENCE_ABSTRACTS,
	INSIDER_INSIGHTS,
	REVIEW_ESSAY,
	DOSSIER,
	SEMINAR_ARTICLE
	
}
